//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carreteras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_carreterasXciudades
    {
        public string car_id { get; set; }
        public string ciu_id { get; set; }
        public string cc_usuario_crea { get; set; }
        public Nullable<System.DateTime> cc_fecha_crea { get; set; }
        public string cc_usuario_modifica { get; set; }
        public Nullable<System.DateTime> cc_fecha_modifica { get; set; }
        public Nullable<bool> cc_estado { get; set; }
    
        public virtual tb_carreteras tb_carreteras { get; set; }
        public virtual tb_ciudades tb_ciudades { get; set; }
        public virtual tb_usuarios tb_usuarios { get; set; }
        public virtual tb_usuarios tb_usuarios1 { get; set; }
    }
}
