//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carreteras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pantallasXroles
    {
        public string rol_id { get; set; }
        public string pant_id { get; set; }
        public string pr_usuario_crea { get; set; }
        public Nullable<System.DateTime> pr_fecha_crea { get; set; }
        public string pr_usuario_modifica { get; set; }
        public Nullable<System.DateTime> pr_fecha_modifica { get; set; }
        public Nullable<bool> pr_estado { get; set; }
    
        public virtual tb_pantallas tb_pantallas { get; set; }
        public virtual tb_roles tb_roles { get; set; }
    }
}
