//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carreteras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tramos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_tramos()
        {
            this.tb_comunas = new HashSet<tb_comunas>();
        }
    
        public string tra_id { get; set; }
        public string tra_descripcion { get; set; }
        public string tra_km_inicio { get; set; }
        public string tra_km_fin { get; set; }
        public string car_id { get; set; }
        public string tra_usuario_crea { get; set; }
        public Nullable<System.DateTime> tra_fecha_crea { get; set; }
        public string tra_usuario_modifica { get; set; }
        public Nullable<System.DateTime> tra_fecha_modifica { get; set; }
        public Nullable<bool> tra_estado { get; set; }
    
        public virtual tb_carreteras tb_carreteras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_comunas> tb_comunas { get; set; }
        public virtual tb_usuarios tb_usuarios { get; set; }
        public virtual tb_usuarios tb_usuarios1 { get; set; }
    }
}
